### ISSUE TITLE
Missing Tiles

### ISSUE THREAD

**Issue by synecdocheNORTH** [LarsWiegers/laravel-maps#33] opened 2022-08-10 13:00 UTC
Hi,

Does anyone have any ideas why the tiles are not fully loading? See screenshot below.

I'm using Bootstrap, but I cannot see where any conflicts are coming from. I've also added my Mapbox API key to my .env file. Using Google works OK but I need multiple instances of the map so I need to use the Leaflet option.

<img width="424" alt="Screenshot 2022-08-10 at 13 59 02" src="https://user-images.githubusercontent.com/43650542/183907239-54184b76-93a0-4b47-91a7-ae1aea7d6ba3.png">

**Comment by LarsWiegers** [comment] 2022-08-10 15:03
Hi! thx for creating the issue.

Without code + console screenshots it is going to be hard to diagnose what is going on.
So pls share your code + what is happening in the console.

**Comment by synecdocheNORTH** [comment] 2022-08-10 15:07
Hi,

Thanks for the response. I am sure it is an issue my side for sure! It's excellent other than this issue I'm having:

<img width="1882" alt="Screenshot 2022-08-10 at 16 05 37" src="https://user-images.githubusercontent.com/43650542/183939156-987f95b2-eb17-48c9-84db-a602de71cca3.png">

`  @foreach ($entry->tasks as $task)
                              <x-maps-leaflet id="marker{{ $task->id }}"
                                                                                class="h-100 w-100" :centerPoint="[
                                                                                    'lat' => $task->address_latitude,
                                                                                    'long' => $task->address_longitude,
                                                                                ]"
                                                                                :markers="[
                                                                                    [
                                                                                        'lat' =>
                                                                                            $task->address_latitude,
                                                                                        'long' =>
                                                                                            $task->address_longitude,
                                                                                    ],
                                                                                ]" :zoomLevel="15">
                                                                            </x-maps-leaflet>
        @endforeach
`

**Comment by LarsWiegers** [comment] 2022-08-10 15:52
We split the marker array up to create an array of markers, can you remove the last , from this: ```$task->address_longitude, ], ]"``` and try again?

**Comment by synecdocheNORTH** [comment] 2022-08-10 16:00
Thanks,

I have set the tileHost and remove the comma. Same result unfortunately.

<img width="1304" alt="Screenshot 2022-08-10 at 17 00 09" src="https://user-images.githubusercontent.com/43650542/183957336-ba54419a-993f-471d-b7c6-bc16f43eeb6c.png">

<img width="406" alt="Screenshot 2022-08-10 at 16 59 26" src="https://user-images.githubusercontent.com/43650542/183957071-ae2811bd-636a-46bd-b0ad-02a2181bc9cb.png">

Network tab: 

<img width="1589" alt="Screenshot 2022-08-10 at 17 00 34" src="https://user-images.githubusercontent.com/43650542/183957427-9368eb93-eb0e-4d3c-bd57-5af4ffb44f52.png">

**Comment by synecdocheNORTH** [comment] 2022-08-10 16:31
Hi,

Actually the network tab has come up with the following:

<img width="975" alt="Screenshot 2022-08-10 at 17 31 28" src="https://user-images.githubusercontent.com/43650542/183964112-77ed5753-c033-47a2-8268-9aba101858dc.png">

**Comment by synecdocheNORTH** [comment] 2022-08-10 17:08
<img width="1917" alt="Screenshot 2022-08-10 at 18 08 03" src="https://user-images.githubusercontent.com/43650542/183974151-5d1530f5-b527-483f-a303-f6bc3fc898c0.png">

**Comment by LarsWiegers** [comment] 2022-08-10 18:39
very weird, almost seems like it would be a bug with leaflet then. going to need to think about this for a bit.

**Comment by synecdocheNORTH** [comment] 2022-08-10 19:35
Ok, thank you for your efforts thus far. They're appreciated.

**Comment by ryangurn** [comment] 2022-08-23 04:11
I am having a similar issue and it appears that it could be caused by the lack of dimensions being provided to the tile layer. I am not entirely sure how to address this but ill continue doing some research.

**Comment by LarsWiegers** [comment] 2022-08-31 16:37
@synecdocheNORTH can you setup a repo that is able to reproduce this? that way we can better test what is going on

**Comment by LarsWiegers** [comment] 2022-09-07 17:32
Closing as @synecdocheNORTH did not respond. feel free to reopen with a reproducable repo

**Closed by LarsWiegers** 2022-09-07 17:32 UTC
Labels: question
